name: Run Tests and Coverage Report

on:
  push:
    
    branches: [ "main", "master" ]
  pull_request:
    
    branches: [ "main", "master" ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run test with coverage 
        run: |
          coverage run -m pytest
      - name: Generate coverage report and check threshold
        run: |
          coverage report -m --fail-under=80
          coverage html

      - name: Upload HTML coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov-report
          path: htmlcov/

